name=OLED_I2C_lib
version=1.0.0
author=emirhan özçelik <emirhanozcelik339@gmail.com>
sentence=128x64 oled ekranlar için kontrol ve kolaylık sağlar
paragraph=oled ekranlarda yazma çizme geometrik ve bitmap içeriklerini çizer 
category=Oled,display
url=https://github.com/EmirhanOzcelik
architectures=*
includes=OLED_LIB.h
